# Generated by Django 6.0.7 on 2026-07-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='foto de perfil'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_quote',
            field=models.CharField(blank=True, help_text='Tu cita de cine favorita, para presumir en el perfil.', max_length=300, verbose_name='frase mítica de cine'),
        ),
    ]
