# Generated by Django 6.0.7 on 2026-07-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar_user_favorite_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quote_streak_best',
            field=models.PositiveIntegerField(default=0, help_text='Récord del juego de Top Secret. Se actualiza solo al jugar.', verbose_name='mejor racha en Frases célebres'),
        ),
    ]
