# Generated by Django 6.0.7 on 2026-07-27 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_quote_streak_best'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite_quote',
        ),
    ]
