# Generated by Django 6.0.7 on 2026-07-31 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_favorite_quote'),
        ('movies', '0003_roulettesavedseen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('essential', 'Imprescindible'), ('suggested', 'Sugerida')], max_length=10, verbose_name='categoría')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='añadida')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='movies.movie', verbose_name='película')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_movies', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'película destacada del perfil',
                'verbose_name_plural': 'perfiles: películas destacadas',
                'ordering': ['category', 'order', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'category', 'movie'), name='una_vez_por_usuario_y_categoria')],
            },
        ),
    ]
