# Generated by Django 6.0.7 on 2026-08-01 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_favoritemovie'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500, unique=True, verbose_name='endpoint')),
                ('p256dh', models.CharField(max_length=255, verbose_name='clave p256dh')),
                ('auth', models.CharField(max_length=255, verbose_name='clave auth')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'suscripción push',
                'verbose_name_plural': 'suscripciones push',
            },
        ),
    ]
