# Generated by Django 6.0.7 on 2026-08-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritemovie',
            name='note',
            field=models.CharField(blank=True, help_text='Opcional — solo tiene sentido en Sugeridas, no en Imprescindibles.', max_length=280, verbose_name='por qué la recomiendas'),
        ),
    ]
