# Generated by Django 6.0.7 on 2026-08-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_googlecalendarconnection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritemovie',
            name='note',
            field=models.CharField(blank=True, help_text='Opcional — visible para cualquiera que vea el perfil, tanto en Imprescindibles como en Sugeridas.', max_length=280, verbose_name='por qué está aquí'),
        ),
    ]
