# Generated by Django 6.0.7 on 2026-08-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_favoritemovie_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritemovie',
            name='note',
        ),
        migrations.AddField(
            model_name='user',
            name='essential_note',
            field=models.TextField(blank=True, help_text='Un único texto para todo el apartado (no por película). Visible para cualquiera que vea tu perfil.', max_length=280, verbose_name='por qué son imprescindibles'),
        ),
        migrations.AddField(
            model_name='user',
            name='suggested_note',
            field=models.TextField(blank=True, help_text='Un único texto para todo el apartado (no por película). Visible para cualquiera que vea tu perfil.', max_length=280, verbose_name='por qué las recomiendas'),
        ),
    ]
