# Generated by Django 6.0.7 on 2026-08-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_favoritemovie_note_user_essential_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rating_duel_streak_best_movie',
            field=models.PositiveIntegerField(default=0, help_text='Récord del juego de Juegos. Se actualiza solo al jugar.', verbose_name='mejor racha en Cuál está mejor valorada (películas)'),
        ),
        migrations.AddField(
            model_name='user',
            name='rating_duel_streak_best_tv',
            field=models.PositiveIntegerField(default=0, help_text='Récord del juego de Juegos. Se actualiza solo al jugar.', verbose_name='mejor racha en Cuál está mejor valorada (series)'),
        ),
    ]
