# Generated by Django 6.0.7 on 2026-08-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_rating_duel_streak_best_movie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hide_pwa_install_prompt',
            field=models.BooleanField(default=False, verbose_name='ocultar sugerencia de instalar la app'),
        ),
        migrations.AddField(
            model_name='user',
            name='show_intro_animation',
            field=models.BooleanField(blank=True, default=None, help_text='Vacío = usa el ajuste del sitio. Marcado/desmarcado = lo fuerza para ti, ajustable en Ajustes.', null=True, verbose_name='animación de intro'),
        ),
    ]
