# Generated by Django 6.0.7 on 2026-08-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_hide_pwa_install_prompt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='essential_note',
            field=models.TextField(blank=True, help_text='Un único texto para todo el apartado (no por película), sin límite de longitud. Visible para cualquiera que vea tu perfil.', verbose_name='por qué son imprescindibles'),
        ),
        migrations.AlterField(
            model_name='user',
            name='suggested_note',
            field=models.TextField(blank=True, help_text='Un único texto para todo el apartado (no por película), sin límite de longitud. Visible para cualquiera que vea tu perfil.', verbose_name='por qué las recomiendas'),
        ),
    ]
