# Generated by Django 6.0.7 on 2026-08-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_essential_note_alter_user_suggested_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='actor_streak_best',
            field=models.PositiveIntegerField(default=0, help_text='Récord del juego de Juegos. Se actualiza solo al jugar.', verbose_name='mejor racha en Cuál tiene al actor/actriz'),
        ),
        migrations.AddField(
            model_name='user',
            name='bad_description_streak_best',
            field=models.PositiveIntegerField(default=0, help_text='Récord del juego de Juegos. Se actualiza solo al jugar.', verbose_name='mejor racha en Malas descripciones'),
        ),
        migrations.AddField(
            model_name='user',
            name='emoji_streak_best',
            field=models.PositiveIntegerField(default=0, help_text='Récord del juego de Juegos. Se actualiza solo al jugar.', verbose_name='mejor racha en Emoji'),
        ),
        migrations.AddField(
            model_name='user',
            name='trivia_streak_best',
            field=models.PositiveIntegerField(default=0, help_text='Récord del juego de Juegos. Se actualiza solo al jugar.', verbose_name='mejor racha en Trivial'),
        ),
        migrations.AddField(
            model_name='user',
            name='true_false_streak_best',
            field=models.PositiveIntegerField(default=0, help_text='Récord del juego de Juegos. Se actualiza solo al jugar.', verbose_name='mejor racha en Verdadero o falso'),
        ),
    ]
