# Generated by Django 6.0.7 on 2026-08-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_actor_streak_best_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='essential_note',
            field=models.TextField(blank=True, help_text='Un único texto para todo el apartado (no por película). Visible para cualquiera que vea tu perfil.', verbose_name='por qué son imprescindibles'),
        ),
        migrations.AlterField(
            model_name='user',
            name='suggested_note',
            field=models.TextField(blank=True, help_text='Un único texto para todo el apartado (no por película). Visible para cualquiera que vea tu perfil.', verbose_name='por qué las recomiendas'),
        ),
    ]
