# Generated by Django 6.0.7 on 2026-08-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_user_essential_note_alter_user_suggested_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='revenue_duel_streak_best',
            field=models.PositiveIntegerField(default=0, help_text='Récord del juego de Juegos. Se actualiza solo al jugar.', verbose_name='mejor racha en Cuál recaudó más'),
        ),
    ]
