# Generated by Django 6.0.7 on 2026-08-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_revenue_duel_streak_best'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notify_new_articles',
            field=models.BooleanField(default=True, verbose_name='avisos por email de artículos nuevos'),
        ),
    ]
