# Generated by Django 6.0.7 on 2026-08-08 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_user_email_notify_new_articles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverificationtoken',
            options={'verbose_name': 'enlace de verificación de email', 'verbose_name_plural': 'cuentas: enlaces de verificación de email'},
        ),
        migrations.AlterModelOptions(
            name='pushsubscription',
            options={'verbose_name': 'dispositivo con notificaciones activadas', 'verbose_name_plural': 'cuentas: dispositivos con notificaciones activadas'},
        ),
    ]
