# Generated by Django 6.0.8 on 2026-08-12 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_user_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritemovie',
            options={'ordering': ['category', 'order', 'created_at'], 'verbose_name': 'película destacada del perfil', 'verbose_name_plural': 'películas destacadas del perfil'},
        ),
        migrations.AlterModelOptions(
            name='pushsubscription',
            options={'verbose_name': 'dispositivo con notificaciones activadas', 'verbose_name_plural': 'dispositivos con notificaciones activadas'},
        ),
    ]
