# Generated by Django 6.0.8 on 2026-08-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_favoritemovie_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notifications_seen_at',
            field=models.DateTimeField(blank=True, help_text='Se actualiza cada vez que abres la campanita de avisos — todo lo anterior a este momento deja de contar en el número, aunque no hayas entrado uno a uno en cada aviso.', null=True, verbose_name='campanita abierta por última vez'),
        ),
    ]
