# Generated by Django 6.0.7 on 2026-07-31 10:01
#
# MovieQuote se recrea aquí solo a nivel de STATE (viene de apps.secret,
# ver secret/migrations/0007_delete_moviequote.py): apunta a la misma tabla
# física ya existente (db_table='secret_moviequote'), así que no hace falta
# ninguna operación real de base de datos para ella. Duel sí es una tabla
# nueva de verdad.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('secret', '0007_delete_moviequote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='MovieQuote',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('quote', models.TextField(verbose_name='frase')),
                        ('correct_title', models.CharField(max_length=255, verbose_name='película correcta')),
                        ('wrong_title_1', models.CharField(max_length=255, verbose_name='opción incorrecta 1')),
                        ('wrong_title_2', models.CharField(max_length=255, verbose_name='opción incorrecta 2')),
                    ],
                    options={
                        'verbose_name': 'frase célebre',
                        'verbose_name_plural': 'frases célebres',
                        'db_table': 'secret_moviequote',
                    },
                ),
            ],
            database_operations=[],
        ),
        migrations.CreateModel(
            name='Duel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'En curso'), ('finished', 'Terminado')], default='active', max_length=10, verbose_name='estado')),
                ('quote_ids', models.JSONField(default=list, verbose_name='frases del duelo (orden fijo)')),
                ('challenger_streak', models.PositiveIntegerField(default=0, verbose_name='racha del retador')),
                ('opponent_streak', models.PositiveIntegerField(default=0, verbose_name='racha del rival')),
                ('challenger_finished', models.BooleanField(default=False, verbose_name='el retador ha terminado')),
                ('opponent_finished', models.BooleanField(default=False, verbose_name='el rival ha terminado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('challenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duels_started', to=settings.AUTH_USER_MODEL, verbose_name='retador')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duels_received', to=settings.AUTH_USER_MODEL, verbose_name='rival')),
            ],
            options={
                'verbose_name': 'duelo',
                'verbose_name_plural': 'duelos',
                'ordering': ['-created_at'],
            },
        ),
    ]
