# Generated by Django 6.0.7 on 2026-07-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duel',
            name='challenger_finished',
        ),
        migrations.RemoveField(
            model_name='duel',
            name='opponent_finished',
        ),
        migrations.AddField(
            model_name='duel',
            name='challenger_answered',
            field=models.BooleanField(default=False, verbose_name='el retador ya respondió esta ronda'),
        ),
        migrations.AddField(
            model_name='duel',
            name='challenger_lost',
            field=models.BooleanField(default=False, verbose_name='el retador falló'),
        ),
        migrations.AddField(
            model_name='duel',
            name='challenger_wants_rematch',
            field=models.BooleanField(default=False, verbose_name='el retador quiere revancha'),
        ),
        migrations.AddField(
            model_name='duel',
            name='current_index',
            field=models.PositiveIntegerField(default=0, verbose_name='ronda actual (compartida)'),
        ),
        migrations.AddField(
            model_name='duel',
            name='opponent_answered',
            field=models.BooleanField(default=False, verbose_name='el rival ya respondió esta ronda'),
        ),
        migrations.AddField(
            model_name='duel',
            name='opponent_lost',
            field=models.BooleanField(default=False, verbose_name='el rival falló'),
        ),
        migrations.AddField(
            model_name='duel',
            name='opponent_wants_rematch',
            field=models.BooleanField(default=False, verbose_name='el rival quiere revancha'),
        ),
        migrations.AlterField(
            model_name='duel',
            name='quote_ids',
            field=models.JSONField(default=list, verbose_name='frases del duelo (orden fijo, compartido)'),
        ),
        migrations.AlterField(
            model_name='duel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('active', 'En curso'), ('finished', 'Terminado')], default='pending', max_length=10, verbose_name='estado'),
        ),
    ]
