# Generated by Django 6.0.7 on 2026-07-31 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_duel_challenger_finished_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='duel',
            name='quote_ids',
            field=models.JSONField(default=list, verbose_name='frases jugadas hasta ahora (compartidas)'),
        ),
        migrations.CreateModel(
            name='DuelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_low_wins', models.PositiveIntegerField(default=0, verbose_name='victorias de player_low')),
                ('player_high_wins', models.PositiveIntegerField(default=0, verbose_name='victorias de player_high')),
                ('draws', models.PositiveIntegerField(default=0, verbose_name='empates')),
                ('player_high', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('player_low', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'marcador de duelos',
                'verbose_name_plural': 'Juegos: marcadores de duelos',
                'constraints': [models.UniqueConstraint(fields=('player_low', 'player_high'), name='un_marcador_por_pareja')],
            },
        ),
    ]
