# Generated by Django 6.0.7 on 2026-07-31 13:10
#
# Limpieza pedida explícitamente: los duelos creados mientras se probaba
# el sistema (con el diseño anterior, asíncrono) no tienen sentido con el
# nuevo formato en directo ni con el marcador (DuelRecord, que arranca de
# cero) — se borran todos para empezar de una vez limpia. A partir de
# ahora, cada Duel se borra solo (apps.games.views.duel_leave) en cuanto
# se sale de la pantalla de resultado, así que esta limpieza puntual no
# debería volver a hacer falta.

from django.db import migrations


def borrar_duelos(apps, schema_editor):
    Duel = apps.get_model("games", "Duel")
    Duel.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_duel_quote_ids_duelrecord'),
    ]

    operations = [
        migrations.RunPython(borrar_duelos, migrations.RunPython.noop),
    ]
