# Generated by Django 6.0.7 on 2026-08-01 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_borra_duelos_anteriores'),
        ('movies', '0005_alter_savedmovie_options_savedmovie_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameTierEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('U', 'Sin clasificar'), ('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='U', max_length=1, verbose_name='nivel')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden dentro del nivel')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='movies.movie', verbose_name='película')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_tier_entries', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'tier list de Juegos: entrada',
                'verbose_name_plural': 'tier list de Juegos: entradas',
                'ordering': ['tier', 'order', 'movie__title'],
                'constraints': [models.UniqueConstraint(fields=('user', 'movie'), name='una_vez_por_usuario_en_tier_de_juegos')],
            },
        ),
    ]
