# Generated by Django 6.0.7 on 2026-08-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_gametierlevel_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviequote',
            name='media_type',
            field=models.CharField(choices=[('movie', 'Película'), ('tv', 'Serie')], default='movie', help_text='Las tres opciones (correcta + 2 incorrectas) deben ser del mismo tipo, para no tener que elegir entre una peli y una serie.', max_length=5, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='moviequote',
            name='correct_title',
            field=models.CharField(max_length=255, verbose_name='título correcto'),
        ),
    ]
