# Generated by Django 6.0.7 on 2026-08-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_moviequote_media_type_alter_moviequote_correct_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriviaQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('trivia', 'Trivial'), ('emoji', 'Emoji'), ('bad_description', 'Malas descripciones'), ('actor', 'Cuál tiene al actor/actriz')], max_length=20, verbose_name='categoría')),
                ('media_type', models.CharField(choices=[('movie', 'Película'), ('tv', 'Serie')], default='movie', help_text='Las tres opciones (correcta + 2 incorrectas) deben ser del mismo tipo, para no tener que elegir entre una peli y una serie.', max_length=5, verbose_name='tipo')),
                ('prompt', models.TextField(help_text='Según la categoría: la pregunta de trivia, la secuencia de emojis, la mala descripción, o el nombre del actor/actriz.', verbose_name='enunciado')),
                ('image_url', models.URLField(blank=True, help_text="Opcional — se usa sobre todo en 'Cuál tiene al actor/actriz' (foto de la persona).", verbose_name='imagen')),
                ('correct_answer', models.CharField(max_length=255, verbose_name='respuesta correcta')),
                ('wrong_answer_1', models.CharField(max_length=255, verbose_name='respuesta incorrecta 1')),
                ('wrong_answer_2', models.CharField(max_length=255, verbose_name='respuesta incorrecta 2')),
            ],
            options={
                'verbose_name': 'pregunta de trivia',
                'verbose_name_plural': 'Juegos: preguntas de trivia',
            },
        ),
        migrations.CreateModel(
            name='TrueFalseStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField(verbose_name='afirmación')),
                ('is_true', models.BooleanField(verbose_name='¿es verdadera?')),
            ],
            options={
                'verbose_name': 'afirmación de verdadero o falso',
                'verbose_name_plural': 'Juegos: verdadero o falso',
            },
        ),
    ]
