# Generated by Django 6.0.7 on 2026-08-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_triviaquestion_truefalsestatement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triviaquestion',
            name='prompt',
            field=models.TextField(help_text='Según la categoría: la pregunta de trivia, la mala descripción, o el nombre del actor/actriz. En Emoji, cada emoji separado por un espacio (se revelan de uno en uno, no todos a la vez): «🦁 👑».', verbose_name='enunciado'),
        ),
    ]
