# Generated by Django 6.0.7 on 2026-08-06 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_alter_triviaquestion_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalityCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='película/serie')),
                ('description', models.TextField(verbose_name='descripción del resultado')),
                ('image_url', models.URLField(blank=True, verbose_name='imagen')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'Qué personaje eres: personaje',
                'verbose_name_plural': 'Juegos: Qué personaje eres — personajes',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PersonalityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='pregunta')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'Qué personaje eres: pregunta',
                'verbose_name_plural': 'Juegos: Qué personaje eres — preguntas',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PersonalityAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='texto')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.personalitycharacter', verbose_name='personaje')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='games.personalityquestion', verbose_name='pregunta')),
            ],
            options={
                'verbose_name': 'Qué personaje eres: respuesta',
                'verbose_name_plural': 'Juegos: Qué personaje eres — respuestas',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
