# Generated by Django 6.0.7 on 2026-08-06 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_personalitycharacter_personalityquestion_and_more'),
        ('movies', '0014_remove_calendardaynote_un_comentario_por_usuario_y_fecha_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OscarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='categoría')),
                ('is_open', models.BooleanField(default=True, verbose_name='abierta a candidaturas y votos')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'Candidatos al Oscar: categoría',
                'verbose_name_plural': 'Juegos: Candidatos al Oscar — categorías',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='OscarCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='propuesta')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='movies.movie', verbose_name='película')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='propuesta por')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='games.oscarcategory', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'Candidatos al Oscar: candidata',
                'verbose_name_plural': 'Juegos: Candidatos al Oscar — candidatas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OscarVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='games.oscarcandidate', verbose_name='candidata')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='games.oscarcategory', verbose_name='categoría')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Candidatos al Oscar: voto',
                'verbose_name_plural': 'Juegos: Candidatos al Oscar — votos',
            },
        ),
        migrations.AddConstraint(
            model_name='oscarcandidate',
            constraint=models.UniqueConstraint(fields=('category', 'movie'), name='una_candidata_por_categoria'),
        ),
        migrations.AddConstraint(
            model_name='oscarvote',
            constraint=models.UniqueConstraint(fields=('category', 'user'), name='un_voto_por_categoria_y_usuario'),
        ),
    ]
