# Generated by Django 6.0.7 on 2026-08-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_oscarcategory_oscarcandidate_oscarvote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duel',
            name='quote_ids',
        ),
        migrations.AddField(
            model_name='duel',
            name='game',
            field=models.CharField(choices=[('quotes', 'Frases célebres'), ('trivia', 'Trivial'), ('bad_description', 'Malas descripciones'), ('actor', 'Cuál tiene al actor/actriz')], default='quotes', max_length=20, verbose_name='juego'),
        ),
        migrations.AddField(
            model_name='duel',
            name='round_ids',
            field=models.JSONField(default=list, verbose_name='preguntas jugadas hasta ahora (compartidas)'),
        ),
    ]
