# Generated by Django 6.0.7 on 2026-08-07 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_remove_duel_quote_ids_duel_game_duel_round_ids'),
        ('movies', '0014_remove_calendardaynote_un_comentario_por_usuario_y_fecha_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='oscarcandidate',
            name='una_candidata_por_categoria',
        ),
        migrations.AddField(
            model_name='oscarcandidate',
            name='person_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='nombre'),
        ),
        migrations.AddField(
            model_name='oscarcandidate',
            name='person_photo_url',
            field=models.URLField(blank=True, verbose_name='foto'),
        ),
        migrations.AddField(
            model_name='oscarcandidate',
            name='person_tmdb_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='id de TMDb'),
        ),
        migrations.AddField(
            model_name='oscarcategory',
            name='candidate_type',
            field=models.CharField(choices=[('movie', 'Película'), ('person', 'Persona (actor/actriz, director/a...)')], default='movie', max_length=10, verbose_name='tipo de candidata'),
        ),
        migrations.AlterField(
            model_name='oscarcandidate',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='movies.movie', verbose_name='película'),
        ),
        migrations.AddConstraint(
            model_name='oscarcandidate',
            constraint=models.UniqueConstraint(fields=('category', 'movie'), name='una_pelicula_candidata_por_categoria'),
        ),
        migrations.AddConstraint(
            model_name='oscarcandidate',
            constraint=models.UniqueConstraint(fields=('category', 'person_tmdb_id'), name='una_persona_candidata_por_categoria'),
        ),
    ]
