# Generated by Django 6.0.8 on 2026-08-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_remove_oscarcandidate_una_candidata_por_categoria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duelrecord',
            options={'verbose_name': 'marcador de duelos', 'verbose_name_plural': 'marcadores de duelos'},
        ),
        migrations.AlterModelOptions(
            name='gametierentry',
            options={'ordering': ['tier__order', 'order', 'movie__title'], 'verbose_name': 'tier list: entrada', 'verbose_name_plural': 'tier list: entradas'},
        ),
        migrations.AlterModelOptions(
            name='gametierlevel',
            options={'ordering': ['user_id', 'order', 'pk'], 'verbose_name': 'tier list: nivel', 'verbose_name_plural': 'tier list: niveles'},
        ),
        migrations.AlterModelOptions(
            name='oscarcandidate',
            options={'ordering': ['-created_at'], 'verbose_name': 'Candidatos al Oscar: candidata', 'verbose_name_plural': 'Candidatos al Oscar — candidatas'},
        ),
        migrations.AlterModelOptions(
            name='oscarcategory',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'Candidatos al Oscar: categoría', 'verbose_name_plural': 'Candidatos al Oscar — categorías'},
        ),
        migrations.AlterModelOptions(
            name='oscarvote',
            options={'verbose_name': 'Candidatos al Oscar: voto', 'verbose_name_plural': 'Candidatos al Oscar — votos'},
        ),
        migrations.AlterModelOptions(
            name='personalityanswer',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'Qué personaje eres: respuesta', 'verbose_name_plural': 'Qué personaje eres — respuestas'},
        ),
        migrations.AlterModelOptions(
            name='personalitycharacter',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'Qué personaje eres: personaje', 'verbose_name_plural': 'Qué personaje eres — personajes'},
        ),
        migrations.AlterModelOptions(
            name='personalityquestion',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'Qué personaje eres: pregunta', 'verbose_name_plural': 'Qué personaje eres — preguntas'},
        ),
        migrations.AlterModelOptions(
            name='triviaquestion',
            options={'verbose_name': 'pregunta de trivia', 'verbose_name_plural': 'preguntas de trivia'},
        ),
        migrations.AlterModelOptions(
            name='truefalsestatement',
            options={'verbose_name': 'afirmación de verdadero o falso', 'verbose_name_plural': 'verdadero o falso'},
        ),
        migrations.AlterField(
            model_name='duel',
            name='game',
            field=models.CharField(choices=[('rating', 'Cuál está mejor valorada'), ('revenue', 'Cuál recaudó más'), ('quotes', 'Frases célebres'), ('trivia', 'Trivial'), ('actor', 'Cuál tiene al actor/actriz'), ('true_false', 'Verdadero o falso'), ('emoji', 'Emoji'), ('bad_description', 'Malas descripciones')], default='quotes', max_length=20, verbose_name='juego'),
        ),
    ]
