# Generated by Django 6.0.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_alter_duelrecord_options_alter_gametierentry_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triviaquestion',
            name='prompt',
            field=models.TextField(help_text='Según la categoría: la pregunta de trivia, la mala descripción, o el nombre del actor/actriz. En Emoji, un único emoji (si escribes varios separados por espacio, solo se enseña el primero): «🦁».', verbose_name='enunciado'),
        ),
    ]
