# Generated by Django 6.0.8 on 2026-09-20 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_alter_triviaquestion_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('media_type', models.CharField(choices=[('movie', 'Película'), ('tv', 'Serie')], default='movie', max_length=5, verbose_name='tipo')),
                ('source_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='nota en Top Secret')),
                ('options', models.JSONField(default=list, help_text='Lista de {"quote": "...", "wrong1": "...", "wrong2": "..."}', verbose_name='opciones')),
                ('resolved', models.BooleanField(default=False, verbose_name='resuelta')),
                ('skipped', models.BooleanField(default=False, verbose_name='descartada')),
                ('chosen_quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='games.moviequote', verbose_name='frase elegida')),
            ],
            options={
                'verbose_name': 'candidata de frase célebre',
                'verbose_name_plural': 'candidatas de frases célebres',
                'ordering': ['-source_rating', 'title'],
            },
        ),
    ]
