# Generated by Django 6.0.7 on 2026-07-26 10:05

import apps.secret.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopSecretConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_code_hash', models.CharField(default=apps.secret.models._default_code_hash, max_length=128, verbose_name='código de acceso (hash)')),
            ],
            options={
                'verbose_name': 'Top Secret: código de acceso',
                'verbose_name_plural': 'Top Secret: código de acceso',
            },
        ),
        migrations.CreateModel(
            name='SecretMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='número')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('personal_rating', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='nota personal')),
                ('comment', models.TextField(blank=True, verbose_name='comentario')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='movies.movie', verbose_name='película del catálogo (opcional, para la portada)')),
            ],
            options={
                'verbose_name': 'película secreta',
                'verbose_name_plural': 'películas secretas',
                'ordering': ['number'],
            },
        ),
    ]
