# Generated by Django 6.0.7 on 2026-07-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(verbose_name='frase')),
                ('correct_title', models.CharField(max_length=255, verbose_name='película correcta')),
                ('wrong_title_1', models.CharField(max_length=255, verbose_name='opción incorrecta 1')),
                ('wrong_title_2', models.CharField(max_length=255, verbose_name='opción incorrecta 2')),
            ],
            options={
                'verbose_name': 'frase célebre',
                'verbose_name_plural': 'frases célebres',
            },
        ),
    ]
