# Generated by Django 6.0.7 on 2026-07-27 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_savedmovie'),
        ('secret', '0002_moviequote'),
    ]

    operations = [
        migrations.CreateModel(
            name='TierListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1, verbose_name='nivel')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden dentro del nivel')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='movies.movie', verbose_name='película del catálogo (opcional, para la portada)')),
            ],
            options={
                'verbose_name': 'entrada de tier list',
                'verbose_name_plural': 'Top Secret: tier list',
                'ordering': ['tier', 'order', 'title'],
            },
        ),
    ]
