# Generated by Django 6.0.7 on 2026-07-27 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0003_tierlistentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='secret_photos/', verbose_name='foto')),
                ('description', models.CharField(blank=True, max_length=280, verbose_name='descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='subida')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='subida por')),
            ],
            options={
                'verbose_name': 'foto del tablón',
                'verbose_name_plural': 'Top Secret: tablón de fotos',
                'ordering': ['-created_at'],
            },
        ),
    ]
