# Generated by Django 6.0.7 on 2026-07-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0004_secretphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tierlistentry',
            name='tier',
            field=models.CharField(choices=[('U', 'Sin clasificar'), ('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='U', max_length=1, verbose_name='nivel'),
        ),
    ]
