# Generated by Django 6.0.7 on 2026-07-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0005_alter_tierlistentry_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nombre')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'género/subgénero',
                'verbose_name_plural': 'géneros/subgéneros',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='secretmovie',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='secret_movies', to='secret.genre', verbose_name='géneros/subgéneros'),
        ),
    ]
