# Generated by Django 6.0.7 on 2026-07-31 10:01
#
# MovieQuote se muda a apps.games para que el admin la agrupe bajo "Juegos"
# en vez de "Top Secret". Esto es solo un cambio de STATE (qué app "es
# dueña" del modelo): la tabla física secret_moviequote no se toca — no hay
# ningún DROP TABLE real, los datos existentes se conservan intactos y la
# migración equivalente en apps.games (0001_initial) vuelve a apuntar a esa
# misma tabla vía db_table.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0006_genre_secretmovie_genres'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='MovieQuote',
                ),
            ],
            database_operations=[],
        ),
    ]
