# Generated by Django 6.0.7 on 2026-07-31 11:27
#
# Primer paso de convertir TierListEntry.tier de un CharField con choices
# fijas (S/A/B/C/D/U) a una FK a TierLevel (nombre/color/orden editables
# desde la propia web). Se añade el nuevo campo (tier_new) SIN tocar el
# viejo todavía, para poder migrar los datos existentes en el siguiente
# paso antes de borrar la columna vieja — así ninguna entrada ya guardada
# se queda huérfana o pierde su nivel.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0007_delete_moviequote'),
    ]

    operations = [
        migrations.CreateModel(
            name='TierLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='nombre')),
                ('color', models.CharField(default='#2DD4BF', max_length=7, verbose_name='color')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'nivel de tier list',
                'verbose_name_plural': 'Top Secret: niveles de tier list',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='tierlistentry',
            name='tier_new',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='entries', to='secret.tierlevel', verbose_name='nivel',
            ),
        ),
    ]
