# Generated by Django 6.0.7 on 2026-07-31 11:27
#
# Segundo paso: crea los niveles S/A/B/C/D con los mismos colores que ya
# tenían fijos por CSS, y reasigna cada TierListEntry existente de su
# antiguo código de texto (tier) al nuevo TierLevel equivalente (tier_new).
# Las que estaban en "U" (Sin clasificar) se quedan con tier_new=None, que
# es exactamente el mismo significado que tenían antes.

from django.db import migrations

DEFAULT_LEVELS = [
    ("S", "#FFD700", 0),
    ("A", "#90EE90", 1),
    ("B", "#87CEEB", 2),
    ("C", "#FFA366", 3),
    ("D", "#D98C8C", 4),
]


def migrate_forward(apps, schema_editor):
    TierLevel = apps.get_model("secret", "TierLevel")
    TierListEntry = apps.get_model("secret", "TierListEntry")

    levels_by_code = {
        code: TierLevel.objects.create(name=code, color=color, order=order)
        for code, color, order in DEFAULT_LEVELS
    }

    for entry in TierListEntry.objects.all():
        entry.tier_new = levels_by_code.get(entry.tier)
        entry.save(update_fields=["tier_new"])


def migrate_backward(apps, schema_editor):
    TierListEntry = apps.get_model("secret", "TierListEntry")
    for entry in TierListEntry.objects.all():
        entry.tier = entry.tier_new.name if entry.tier_new else "U"
        entry.save(update_fields=["tier"])


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0008_tierlevel'),
    ]

    operations = [
        migrations.RunPython(migrate_forward, migrate_backward),
    ]
