# Generated by Django 6.0.7 on 2026-07-31 11:27
#
# Último paso: ya migrados los datos (0009), se borra la columna vieja
# (tier, CharField) y se renombra tier_new a tier.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0009_migrate_tier_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tierlistentry',
            name='tier',
        ),
        migrations.RenameField(
            model_name='tierlistentry',
            old_name='tier_new',
            new_name='tier',
        ),
        migrations.AlterModelOptions(
            name='tierlistentry',
            options={
                'ordering': ['tier__order', 'order', 'title'],
                'verbose_name': 'entrada de tier list',
                'verbose_name_plural': 'Top Secret: tier list',
            },
        ),
    ]
