# Generated by Django 6.0.7 on 2026-08-02 17:06

from django.db import migrations, models


def renumber_by_rating(apps, schema_editor):
    """El número deja de ser un valor a mano y pasa a ser la posición al
    ordenar todas las películas secretas por nota (de mayor a menor);
    `tie_break` (0 para todas las que ya existían) solo decide el orden
    entre dos con la misma nota. Se recalcula aquí una vez para que los
    datos que ya hubiera queden consistentes con la nueva regla.

    Dos pasadas (primero a valores temporales muy por encima de cualquier
    posición real, luego a la posición definitiva) para no chocar con el
    UniqueConstraint de `number` a media actualización — y como es un
    PositiveIntegerField, el valor temporal tiene que ser positivo."""
    SecretMovie = apps.get_model("secret", "SecretMovie")
    ordered = list(SecretMovie.objects.order_by("-personal_rating", "tie_break", "pk"))
    targets = [
        (movie, position) for position, movie in enumerate(ordered, start=1)
        if movie.number != position
    ]
    if not targets:
        return

    temp_base = len(ordered) + 1
    for offset, (movie, _) in enumerate(targets, start=1):
        movie.number = temp_base + offset
    SecretMovie.objects.bulk_update([movie for movie, _ in targets], ["number"])

    for movie, final_number in targets:
        movie.number = final_number
    SecretMovie.objects.bulk_update([movie for movie, _ in targets], ["number"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0010_finalize_tier_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretmovie',
            name='tie_break',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Solo importa entre dos películas con la misma nota: la de menor valor aquí sale antes en el número.', verbose_name='orden de desempate'),
        ),
        migrations.AlterField(
            model_name='secretmovie',
            name='number',
            field=models.PositiveIntegerField(default=0, editable=False, unique=True, verbose_name='número'),
        ),
        migrations.RunPython(renumber_by_rating, noop),
    ]
