# Generated by Django 6.0.7 on 2026-08-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0011_secretmovie_tie_break_alter_secretmovie_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'verbose_name': 'lista', 'verbose_name_plural': 'listas'},
        ),
        migrations.AlterField(
            model_name='secretmovie',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='secret_movies', to='secret.genre', verbose_name='listas'),
        ),
    ]
