# Generated by Django 6.0.7 on 2026-08-04 17:37, hand-edited:
# - El tier list y el tablón de fotos pasan a ser personales por usuario
#   (campos `user`/`board_owner` en dos fases: aquí opcionales, obligatorios
#   en la 0015, ya con la tabla vacía tras la 0013).
# - ReleaseEvent/CalendarDayNote se mudan aquí desde movies (misma tabla
#   física, solo cambia el estado de Django — SeparateDatabaseAndState con
#   database_operations=[] para no tocar la base de datos real).

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_remove_calendardaynote_un_comentario_por_usuario_y_fecha_and_more'),
        ('secret', '0013_wipe_tierlist_and_photos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tierlevel',
            options={'ordering': ['user_id', 'order', 'pk'], 'verbose_name': 'nivel de tier list', 'verbose_name_plural': 'Top Secret: niveles de tier list'},
        ),
        migrations.AlterModelOptions(
            name='tierlistentry',
            options={'ordering': ['user_id', 'tier__order', 'order', 'title'], 'verbose_name': 'entrada de tier list', 'verbose_name_plural': 'Top Secret: tier list'},
        ),
        migrations.AddField(
            model_name='secretphoto',
            name='board_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo_board_photos', to=settings.AUTH_USER_MODEL, verbose_name='tablón de'),
        ),
        migrations.AddField(
            model_name='tierlevel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tier_levels', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AddField(
            model_name='tierlistentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tier_entries', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='secretphoto',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='subida por'),
        ),
        migrations.CreateModel(
            name='PhotoBoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_at', models.DateTimeField(auto_now_add=True, verbose_name='invitado')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_photo_boards', to=settings.AUTH_USER_MODEL, verbose_name='invitado')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_board_members', to=settings.AUTH_USER_MODEL, verbose_name='dueño del tablón')),
            ],
            options={
                'verbose_name': 'acceso al tablón de fotos',
                'verbose_name_plural': 'Top Secret: accesos al tablón de fotos',
                'constraints': [models.UniqueConstraint(fields=('owner', 'member'), name='un_acceso_por_dueno_y_miembro')],
            },
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='ReleaseEvent',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('date', models.DateField(verbose_name='fecha')),
                        ('note', models.CharField(blank=True, help_text="Ej: 'Estreno', 'Temporada 2', 'Capítulo final'...", max_length=200, verbose_name='nota')),
                        ('google_event_id', models.CharField(blank=True, max_length=255, verbose_name='id del evento en Google Calendar')),
                        ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='movies.movie', verbose_name='película/serie')),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_events', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
                    ],
                    options={
                        'verbose_name': 'estreno en el calendario',
                        'verbose_name_plural': 'Top Secret: calendario, estrenos',
                        'db_table': 'movies_releaseevent',
                        'ordering': ['date'],
                    },
                ),
                migrations.CreateModel(
                    name='CalendarDayNote',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('date', models.DateField(verbose_name='fecha')),
                        ('note', models.CharField(max_length=280, verbose_name='comentario')),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_day_notes', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
                    ],
                    options={
                        'verbose_name': 'comentario del calendario',
                        'verbose_name_plural': 'Top Secret: calendario, comentarios de días',
                        'db_table': 'movies_calendardaynote',
                        'ordering': ['date'],
                        'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='un_comentario_por_usuario_y_fecha')],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
