# Generated by Django 6.0.7 on 2026-08-04 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0014_tierlist_photos_personal_and_calendar_move'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretphoto',
            name='board_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_board_photos', to=settings.AUTH_USER_MODEL, verbose_name='tablón de'),
        ),
        migrations.AlterField(
            model_name='secretphoto',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='subida por'),
        ),
        migrations.AlterField(
            model_name='tierlevel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_levels', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='tierlistentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_entries', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
    ]
