# Generated by Django 6.0.7 on 2026-08-05 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0015_alter_secretphoto_board_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photoboardmember',
            options={'verbose_name': 'permiso al tablón de fotos', 'verbose_name_plural': 'Top Secret: permisos al tablón de fotos'},
        ),
    ]
