# Generated by Django 6.0.7 on 2026-08-06 16:42

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0016_alter_photoboardmember_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretphoto',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(), upload_to='secret_photos/', verbose_name='foto'),
        ),
    ]
