# Generated by Django 6.0.7 on 2026-08-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0017_alter_secretphoto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendardaynote',
            name='note',
            field=models.TextField(verbose_name='comentario'),
        ),
    ]
