# Generated by Django 6.0.7 on 2026-08-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0018_alter_calendardaynote_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topsecretconfig',
            options={'verbose_name': 'Top Secret: código de acceso y colores', 'verbose_name_plural': 'Top Secret: código de acceso y colores'},
        ),
        migrations.AddField(
            model_name='secretmovie',
            name='rating_verdict',
            field=models.CharField(blank=True, choices=[('sobrevalorada', 'Sobrevalorada'), ('bien_valorada', 'Bien valorada'), ('infravalorada', 'Infravalorada')], default='', help_text='¿Tu nota está por encima, por debajo o acorde con lo que de verdad merece? Opcional.', max_length=20, verbose_name='evaluación real'),
        ),
        migrations.AddField(
            model_name='topsecretconfig',
            name='color_rating_bad',
            field=models.CharField(default='#EF4444', max_length=7, verbose_name='color de nota baja'),
        ),
        migrations.AddField(
            model_name='topsecretconfig',
            name='color_rating_good',
            field=models.CharField(default='#22C55E', max_length=7, verbose_name='color de nota alta'),
        ),
        migrations.AddField(
            model_name='topsecretconfig',
            name='color_rating_mid',
            field=models.CharField(default='#FFB347', max_length=7, verbose_name='color de nota media'),
        ),
        migrations.AddField(
            model_name='topsecretconfig',
            name='rating_good_threshold',
            field=models.DecimalField(decimal_places=1, default=8.0, max_digits=3, verbose_name='nota a partir de la cual se considera alta'),
        ),
        migrations.AddField(
            model_name='topsecretconfig',
            name='rating_mid_threshold',
            field=models.DecimalField(decimal_places=1, default=6.0, help_text='Por debajo de esta nota se considera baja.', max_digits=3, verbose_name='nota a partir de la cual se considera media'),
        ),
    ]
