# Generated by Django 6.0.8 on 2026-08-12 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0019_alter_topsecretconfig_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendardaynote',
            options={'ordering': ['date'], 'verbose_name': 'comentario del calendario', 'verbose_name_plural': 'comentarios del calendario'},
        ),
        migrations.AlterModelOptions(
            name='photoboardmember',
            options={'verbose_name': 'permiso al tablón de fotos', 'verbose_name_plural': 'permisos al tablón de fotos'},
        ),
        migrations.AlterModelOptions(
            name='releaseevent',
            options={'ordering': ['date'], 'verbose_name': 'estreno en el calendario', 'verbose_name_plural': 'estrenos en el calendario'},
        ),
        migrations.AlterModelOptions(
            name='secretphoto',
            options={'ordering': ['-created_at'], 'verbose_name': 'foto del tablón', 'verbose_name_plural': 'tablón de fotos'},
        ),
        migrations.AlterModelOptions(
            name='tierlevel',
            options={'ordering': ['user_id', 'order', 'pk'], 'verbose_name': 'tier list: nivel', 'verbose_name_plural': 'tier list: niveles'},
        ),
        migrations.AlterModelOptions(
            name='tierlistentry',
            options={'ordering': ['user_id', 'tier__order', 'order', 'title'], 'verbose_name': 'tier list: entrada', 'verbose_name_plural': 'tier list: entradas'},
        ),
        migrations.AlterModelOptions(
            name='topsecretconfig',
            options={'verbose_name': 'código de acceso y colores', 'verbose_name_plural': 'código de acceso y colores'},
        ),
    ]
