# Generated by Django 6.0.8 on 2026-08-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0020_alter_calendardaynote_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='admin_only',
            field=models.BooleanField(default=False, help_text='Ni esta lista ni ninguna película marcada con ella las ve nadie más, aunque tenga el código.', verbose_name='solo para admins'),
        ),
    ]
