# Generated by Django 6.0.8 on 2026-08-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0021_genre_admin_only'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['order', 'name'], 'verbose_name': 'lista', 'verbose_name_plural': 'listas'},
        ),
        migrations.AddField(
            model_name='genre',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='orden'),
        ),
    ]
