# Generated by Django 6.0.8 on 2026-08-14 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0022_alter_genre_options_genre_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretmovie',
            name='rating_verdict',
        ),
    ]
