# Generated by Django 6.0.8 on 2026-08-14 11:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def seed_default_bands(apps, schema_editor):
    """Antes de este cambio los colores eran fijos: >=8 verde, >=6 naranja,
    resto rojo. Se recrean como tramos normales para que las notas ya
    puestas no se queden todas en gris nada más migrar."""
    TopSecretConfig = apps.get_model('secret', 'TopSecretConfig')
    RatingColorBand = apps.get_model('secret', 'RatingColorBand')
    config = TopSecretConfig.objects.first()
    if config is None:
        return
    RatingColorBand.objects.bulk_create([
        RatingColorBand(config=config, min_rating='8.0', max_rating='10.0', color='#22C55E', order=0),
        RatingColorBand(config=config, min_rating='6.0', max_rating='7.9', color='#FFB347', order=1),
        RatingColorBand(config=config, min_rating='0.0', max_rating='5.9', color='#EF4444', order=2),
    ])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0023_remove_secretmovie_rating_verdict'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secretmovie',
            options={'ordering': ['number'], 'verbose_name': 'entrada a la lista completa', 'verbose_name_plural': 'películas secretas'},
        ),
        migrations.RemoveField(
            model_name='topsecretconfig',
            name='color_rating_bad',
        ),
        migrations.RemoveField(
            model_name='topsecretconfig',
            name='color_rating_good',
        ),
        migrations.RemoveField(
            model_name='topsecretconfig',
            name='color_rating_mid',
        ),
        migrations.RemoveField(
            model_name='topsecretconfig',
            name='rating_good_threshold',
        ),
        migrations.RemoveField(
            model_name='topsecretconfig',
            name='rating_mid_threshold',
        ),
        migrations.CreateModel(
            name='RatingColorBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_rating', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='nota mínima')),
                ('max_rating', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='nota máxima')),
                ('color', models.CharField(default='#9CA3AF', max_length=7, validators=[django.core.validators.RegexValidator(message='Usa un color hexadecimal, ej. #0D9488', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='color')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_bands', to='secret.topsecretconfig')),
            ],
            options={
                'verbose_name': 'tramo de color',
                'verbose_name_plural': 'tramos de color',
                'ordering': ['order', 'min_rating'],
            },
        ),
        migrations.RunPython(seed_default_bands, noop),
    ]
