# Generated by Django 6.0.8 on 2026-08-15 13:38

from django.db import migrations, models

DEFAULT_RATING_GUIDE = """Para que una película suspenda tiene que ser realmente mala, a mí me parece que casi todo merece una oportunidad y esa oportunidad se traduce en el 5.
A partir del 8 se mira con lupa porque al igual que me gusta todo no puedo dar a todo una notaza, tiene que haber un criterio mínimo.
Las películas animadas están sobrepuntuadas porque la animación me gusta mucho, para mí el mejor formato.
El anime por el contrario puede estar infracalificado porque me cuesta verlo y muchas veces me aburre por el formato.
Las películas de terror son polarizantes, o me encantan o las odio.
Las películas de cine pueden estar sobrecalificadas por dónde y con quién las vi.
Cualquier película de acción que no sea realmente mala llegará al 6 pero difícilmente al 8.
Si alguna película es especial para mí la voy a inflar como un globo y me la pela, es mi lista.
Si alguna película aunque no sea tan mala me ha hecho dormirme se va al 2 de cabeza."""


def seed_rating_guide(apps, schema_editor):
    TopSecretConfig = apps.get_model('secret', 'TopSecretConfig')
    config = TopSecretConfig.objects.first()
    if config is not None and not config.rating_guide:
        config.rating_guide = DEFAULT_RATING_GUIDE
        config.save(update_fields=['rating_guide'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0024_alter_secretmovie_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topsecretconfig',
            name='rating_guide',
            field=models.TextField(blank=True, help_text='Explica tu criterio a la hora de puntuar (qué hunde una nota, qué la infla...). Se enseña colapsada, en un desplegable, en la lista completa.', verbose_name='guía para entender la lista'),
        ),
        migrations.RunPython(seed_rating_guide, noop),
    ]
