# Generated by Django 6.0.8 on 2026-08-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0025_topsecretconfig_rating_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretmovie',
            name='series_watch_status',
            field=models.CharField(blank=True, choices=[('not_watched', 'No vista'), ('airing', 'En emisión'), ('watched', 'Vista')], default='not_watched', max_length=20, verbose_name='estado de visionado (series)'),
        ),
    ]
