# Generated by Django 6.0.8 on 2026-08-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0026_secretmovie_series_watch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='topsecretconfig',
            name='allow_web_editing',
            field=models.BooleanField(default=False, help_text='Mientras esté activo, en Lista completa se puede cambiar la nota, el desempate y las listas de cada película sin pasar por el admin, y hay una pantalla para crear/borrar listas. Es un interruptor tuyo: actívalo cuando quieras revisar algo desde el móvil y desactívalo cuando termines — con esto en no, la web vuelve a ser de solo lectura.', verbose_name='permitir editar nota y listas desde la web'),
        ),
        migrations.AlterField(
            model_name='secretmovie',
            name='tie_break',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Solo importa entre dos películas con la misma nota: la de mayor valor aquí sale antes en el número.', verbose_name='orden de desempate'),
        ),
    ]
