# Generated by Django 6.0.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0027_topsecretconfig_allow_web_editing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretmovie',
            name='admin_only',
            field=models.BooleanField(default=False, help_text='Oculta esta película para cualquiera que no sea Admin, aunque tenga el código y esté en una lista pública. Publícala cuando quieras desmarcando esto.', verbose_name='solo para admins'),
        ),
    ]
