# Generated by Django 6.0.8 on 2026-08-27 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_movie_revenue'),
        ('secret', '0028_secretmovie_admin_only'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretListMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_at', models.DateTimeField(auto_now_add=True, verbose_name='invitado')),
            ],
            options={
                'verbose_name': 'permiso a la lista propia',
                'verbose_name_plural': 'permisos a la lista propia',
            },
        ),
        migrations.AddField(
            model_name='genre',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='own_secret_genres', to=settings.AUTH_USER_MODEL, verbose_name='dueño (vacío = lista de Bygui)'),
        ),
        migrations.AddField(
            model_name='secretmovie',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='own_secret_movies', to=settings.AUTH_USER_MODEL, verbose_name='dueño (vacío = lista de Bygui)'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='admin_only',
            field=models.BooleanField(default=False, help_text='Ni esta lista ni ninguna película marcada con ella las ve nadie más, aunque tenga el código. Solo aplica a las listas de Bygui.', verbose_name='solo para admins'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='secretmovie',
            name='number',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='número'),
        ),
        migrations.AddConstraint(
            model_name='genre',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('name',), name='nombre_unico_listas_bygui'),
        ),
        migrations.AddConstraint(
            model_name='genre',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('owner', 'name'), name='nombre_unico_por_dueno'),
        ),
        migrations.AddConstraint(
            model_name='genre',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('slug',), name='slug_unico_listas_bygui'),
        ),
        migrations.AddConstraint(
            model_name='genre',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('owner', 'slug'), name='slug_unico_por_dueno'),
        ),
        migrations.AddConstraint(
            model_name='secretmovie',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('number',), name='numero_unico_lista_bygui'),
        ),
        migrations.AddConstraint(
            model_name='secretmovie',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('owner', 'number'), name='numero_unico_por_dueno'),
        ),
        migrations.AddField(
            model_name='secretlistmember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_secret_lists', to=settings.AUTH_USER_MODEL, verbose_name='invitado'),
        ),
        migrations.AddField(
            model_name='secretlistmember',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secret_list_members', to=settings.AUTH_USER_MODEL, verbose_name='dueño de la lista'),
        ),
        migrations.AddConstraint(
            model_name='secretlistmember',
            constraint=models.UniqueConstraint(fields=('owner', 'member'), name='un_acceso_por_dueno_y_miembro_lista'),
        ),
    ]
