# Generated by Django 6.0.8 on 2026-08-28 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0029_secretlistmember_genre_owner_secretmovie_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarShareMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_at', models.DateTimeField(auto_now_add=True, verbose_name='invitado')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_calendars', to=settings.AUTH_USER_MODEL, verbose_name='invitado')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_share_members', to=settings.AUTH_USER_MODEL, verbose_name='dueño del calendario')),
            ],
            options={
                'verbose_name': 'permiso al calendario',
                'verbose_name_plural': 'permisos al calendario',
                'constraints': [models.UniqueConstraint(fields=('owner', 'member'), name='un_acceso_por_dueno_y_miembro_calendario')],
            },
        ),
    ]
