# Generated by Django 6.0.8 on 2026-08-31 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0030_calendarsharemember'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopSecretTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('lista', 'Lista'), ('calendario', 'Calendario'), ('tablon', 'Tablón'), ('buscar', 'Buscar'), ('amigos', 'Amigos'), ('guardados', 'Guardados')], editable=False, max_length=20, unique=True, verbose_name='pestaña')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'orden de pestaña',
                'verbose_name_plural': 'orden de las pestañas de arriba',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='secretmovie',
            options={'ordering': ['number'], 'verbose_name': 'entrada a la lista completa', 'verbose_name_plural': 'películas enlistadas'},
        ),
    ]
