# Generated by Django 6.0.8

from django.db import migrations

# Mismo orden que tenía la barra hasta ahora, hardcodeado en
# templates/secret/_shell.html -- sembrar con esto hace que nada cambie
# visualmente hasta que alguien lo reordene de verdad desde el admin.
DEFAULT_ORDER = ["lista", "calendario", "tablon", "buscar", "amigos", "guardados"]


def seed_default_order(apps, schema_editor):
    TopSecretTab = apps.get_model("secret", "TopSecretTab")
    TopSecretTab.objects.bulk_create(
        [TopSecretTab(key=key, order=position) for position, key in enumerate(DEFAULT_ORDER)],
        ignore_conflicts=True,
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("secret", "0031_topsecrettab_alter_secretmovie_options"),
    ]

    operations = [
        migrations.RunPython(seed_default_order, noop_reverse),
    ]
