# Generated by Django 6.0.8 on 2026-09-01 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0032_seed_topsecrettab_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='admin_only',
            field=models.BooleanField(default=False, help_text='Ni esta lista ni ninguna película marcada con ella las ve nadie más, aunque tenga el código. Solo aplica a las listas de lasaladebygui.', verbose_name='solo para admins'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='own_secret_genres', to=settings.AUTH_USER_MODEL, verbose_name='dueño (vacío = lista de lasaladebygui)'),
        ),
        migrations.AlterField(
            model_name='secretmovie',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='own_secret_movies', to=settings.AUTH_USER_MODEL, verbose_name='dueño (vacío = lista de lasaladebygui)'),
        ),
    ]
