# Generated by Django 6.0.8 on 2026-10-04 15:41

import django.core.validators
import django.db.models.deletion
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_movie_revenue'),
        ('secret', '0034_rating_guide_per_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='nombre')),
                ('emoji', models.CharField(help_text='Se usa como icono del póster en la tira de estrenos del calendario, p. ej. 🩸', max_length=8, verbose_name='emoji')),
                ('color', models.CharField(default='#00e5ff', max_length=7, validators=[django.core.validators.RegexValidator(message='Usa un color hexadecimal, ej. #0D9488', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='color')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'categoría de cine',
                'verbose_name_plural': 'categorías de cine',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='secretphoto',
            name='image',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(access_key='df0b4bb6d7812b5b554800a4e235e193', addressing_style='path', bucket_name='media', endpoint_url='https://xpleukpsphqwuvshyyls.storage.supabase.co/storage/v1/s3', file_overwrite=False, querystring_auth=True, querystring_expire=60, region_name='us-east-1', secret_key=''), upload_to='secret_photos/', verbose_name='foto'),
        ),
        migrations.CreateModel(
            name='CinemaRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('release_date', models.DateField(verbose_name='fecha de estreno')),
                ('note', models.CharField(blank=True, help_text='Ej: «Secuela», «Solo en VOSE»...', max_length=120, verbose_name='nota')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='releases', to='secret.cinemacategory', verbose_name='categoría')),
                ('movie', models.ForeignKey(blank=True, help_text='Si ya está en el catálogo, enlaza su ficha desde la tira. Si no, déjalo vacío.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='movies.movie', verbose_name='película del catálogo (opcional)')),
            ],
            options={
                'verbose_name': 'estreno en cines',
                'verbose_name_plural': 'estrenos en cines',
                'ordering': ['release_date', 'title'],
            },
        ),
    ]
