# Generated by Django 6.0.8 on 2026-10-04 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0035_cinemacategory_alter_secretphoto_image_cinemarelease'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendardaynote',
            options={'ordering': ['date'], 'verbose_name': 'comentario del calendario', 'verbose_name_plural': 'calendario: comentarios'},
        ),
        migrations.AlterModelOptions(
            name='calendarsharemember',
            options={'verbose_name': 'permiso al calendario', 'verbose_name_plural': 'calendario: permisos para compartir'},
        ),
        migrations.AlterModelOptions(
            name='cinemacategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'categoría de cine', 'verbose_name_plural': 'cartelera: categorías'},
        ),
        migrations.AlterModelOptions(
            name='cinemarelease',
            options={'ordering': ['release_date', 'title'], 'verbose_name': 'estreno en cines', 'verbose_name_plural': 'cartelera: estrenos'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['order', 'name'], 'verbose_name': 'lista: tema', 'verbose_name_plural': 'lista: temas'},
        ),
        migrations.AlterModelOptions(
            name='photoboardmember',
            options={'verbose_name': 'permiso al tablón de fotos', 'verbose_name_plural': 'tablón: permisos para compartir'},
        ),
        migrations.AlterModelOptions(
            name='ratingguide',
            options={'verbose_name': 'ajustes: guía y colores (por cuenta)', 'verbose_name_plural': 'ajustes: guía y colores (por cuenta)'},
        ),
        migrations.AlterModelOptions(
            name='releaseevent',
            options={'ordering': ['date'], 'verbose_name': 'estreno que sigo', 'verbose_name_plural': 'calendario: estrenos que sigo'},
        ),
        migrations.AlterModelOptions(
            name='secretlistmember',
            options={'verbose_name': 'permiso a la lista propia', 'verbose_name_plural': 'lista: permisos para compartir'},
        ),
        migrations.AlterModelOptions(
            name='secretmovie',
            options={'ordering': ['number'], 'verbose_name': 'entrada a la lista completa', 'verbose_name_plural': 'lista: películas'},
        ),
        migrations.AlterModelOptions(
            name='secretphoto',
            options={'ordering': ['-created_at'], 'verbose_name': 'foto del tablón', 'verbose_name_plural': 'tablón: fotos'},
        ),
        migrations.AlterModelOptions(
            name='topsecretconfig',
            options={'verbose_name': 'ajustes: código de acceso al maletín', 'verbose_name_plural': 'ajustes: código de acceso al maletín'},
        ),
        migrations.AlterModelOptions(
            name='topsecrettab',
            options={'ordering': ['order'], 'verbose_name': 'orden de pestaña', 'verbose_name_plural': 'ajustes: orden de las pestañas de arriba'},
        ),
    ]
