from django.urls import path

from . import views

app_name = "secret"

urlpatterns = [
    path("", views.gate, name="gate"),
    path("cerrar/", views.lock, name="lock"),
    path("dentro/", views.home, name="home"),
    path("dentro/numero/", views.by_number, name="by-number"),
    path("dentro/nota/", views.by_rating, name="by-rating"),
    path("dentro/lista/", views.full_list, name="list"),
    path("dentro/lista/<int:pk>/", views.movie_detail, name="movie-detail"),
    path("dentro/lista/<int:pk>/visto/", views.movie_watch_cycle, name="movie-watch-cycle"),
    path("dentro/lista/<int:pk>/editar/", views.movie_quick_edit, name="movie-quick-edit"),
    path("dentro/lista/<int:pk>/editar/portada/buscar/", views.movie_poster_search, name="movie-poster-search"),
    path("dentro/lista/<int:pk>/editar/portada/quitar/", views.movie_poster_remove, name="movie-poster-remove"),
    path("dentro/lista/<int:pk>/editar/portada/<int:tmdb_id>/", views.movie_poster_set, name="movie-poster-set"),
    path("dentro/listas/", views.genre_manage, name="genre-manage"),
    path("dentro/listas/<int:pk>/borrar/", views.genre_delete, name="genre-delete"),
    path("dentro/lista/mia/buscar/", views.own_movie_add_search, name="own-movie-add-search"),
    path("dentro/lista/mia/anadir/<int:tmdb_id>/", views.own_movie_add, name="own-movie-add"),
    path("dentro/lista/mia/<int:pk>/borrar/", views.own_movie_delete, name="own-movie-delete"),
    path("dentro/compartidos/", views.shared_hub, name="shared-hub"),
    path("dentro/comparar/", views.compare_lists, name="compare"),
    path("dentro/lista/compartir/", views.own_list_share, name="own-list-share"),
    path("dentro/lista/compartir/invitar/<str:username>/", views.own_list_share_invite, name="own-list-share-invite"),
    path("dentro/lista/compartir/expulsar/<int:pk>/", views.own_list_share_kick, name="own-list-share-kick"),
    path("dentro/otros/", views.other, name="other"),
    path("dentro/tierlist/", views.tier_list, name="tier-list"),
    path("dentro/tierlist/compartir/", views.tier_list_share_image, name="tier-list-share-image"),
    path("dentro/tierlist/buscar/", views.tier_list_search, name="tier-list-search"),
    path("dentro/tierlist/anadir/<int:tmdb_id>/", views.tier_list_add, name="tier-list-add"),
    path("dentro/tierlist/<int:pk>/mover/", views.tier_list_move, name="tier-list-move"),
    path("dentro/tierlist/reiniciar/", views.tier_list_reset, name="tier-list-reset"),
    path("dentro/tierlist/niveles/anadir/", views.tier_level_create, name="tier-level-create"),
    path("dentro/tierlist/niveles/<int:pk>/editar/", views.tier_level_update, name="tier-level-update"),
    path("dentro/tierlist/niveles/<int:pk>/borrar/", views.tier_level_delete, name="tier-level-delete"),
    path("dentro/tablon/", views.photo_board, name="photo-board"),
    path("dentro/tablon/subir/", views.photo_board_upload, name="photo-board-upload"),
    path("dentro/tablon/foto/<int:pk>/", views.photo_serve, name="photo-serve"),
    path("dentro/tablon/foto/<int:pk>/editar/", views.photo_board_edit, name="photo-board-edit"),
    path("dentro/tablon/foto/<int:pk>/borrar/", views.photo_board_delete, name="photo-board-delete"),
    path("dentro/tablon/invitar/<str:username>/", views.photo_board_invite, name="photo-board-invite"),
    path("dentro/tablon/expulsar/<int:pk>/", views.photo_board_kick, name="photo-board-kick"),
    path("dentro/tablon/<str:username>/", views.photo_board, name="photo-board-shared"),
    path("dentro/tablon/<str:username>/subir/", views.photo_board_upload, name="photo-board-upload-shared"),
    path("dentro/calendario/", views.calendar_view, name="calendar"),
    path("dentro/calendario/imagen/", views.calendar_share_image, name="calendar-share-image"),
    path("dentro/calendario/compartir/", views.calendar_share, name="calendar-share"),
    path("dentro/calendario/compartir/invitar/<str:username>/", views.calendar_share_invite, name="calendar-share-invite"),
    path("dentro/calendario/compartir/expulsar/<int:pk>/", views.calendar_share_kick, name="calendar-share-kick"),
    path("dentro/calendario/buscar/", views.calendar_search, name="calendar-search"),
    path("dentro/calendario/anadir/<str:media_type>/<int:tmdb_id>/", views.calendar_add, name="calendar-add"),
    path("dentro/calendario/<int:pk>/quitar/", views.calendar_remove, name="calendar-remove"),
    path("dentro/calendario/<int:pk>/mover/", views.calendar_move_event, name="calendar-move"),
    path("dentro/calendario/nota/", views.calendar_day_note, name="calendar-day-note"),
    path("dentro/calendario/<str:username>/", views.calendar_view, name="calendar-shared"),
]
