# Generated by Django 5.1.15 on 2026-07-26 09:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='nombre')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='identificador')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='descripción breve')),
                ('color_bg', models.CharField(default='#0B1416', max_length=7, validators=[django.core.validators.RegexValidator(message='Usa un color hexadecimal, ej. #0D9488', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='fondo principal')),
                ('color_surface', models.CharField(default='#122120', max_length=7, validators=[django.core.validators.RegexValidator(message='Usa un color hexadecimal, ej. #0D9488', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='fondo de tarjetas/paneles')),
                ('color_border', models.CharField(default='#1F2E2D', max_length=7, validators=[django.core.validators.RegexValidator(message='Usa un color hexadecimal, ej. #0D9488', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='color de bordes')),
                ('color_text', models.CharField(default='#E5E7EB', max_length=7, validators=[django.core.validators.RegexValidator(message='Usa un color hexadecimal, ej. #0D9488', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='texto primario')),
                ('color_text_muted', models.CharField(default='#9CA3AF', max_length=7, validators=[django.core.validators.RegexValidator(message='Usa un color hexadecimal, ej. #0D9488', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='texto secundario')),
                ('color_accent', models.CharField(default='#2DD4BF', max_length=7, validators=[django.core.validators.RegexValidator(message='Usa un color hexadecimal, ej. #0D9488', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='acento principal (enlaces, titulares destacados)')),
                ('color_accent_hover', models.CharField(default='#5EEAD4', max_length=7, validators=[django.core.validators.RegexValidator(message='Usa un color hexadecimal, ej. #0D9488', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='acento principal — hover')),
                ('color_on_accent', models.CharField(default='#0B1416', max_length=7, validators=[django.core.validators.RegexValidator(message='Usa un color hexadecimal, ej. #0D9488', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='texto sobre el acento principal')),
                ('color_accent_secondary', models.CharField(default='#FFB347', max_length=7, validators=[django.core.validators.RegexValidator(message='Usa un color hexadecimal, ej. #0D9488', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='acento secundario (botones, CTA)')),
                ('color_accent_secondary_hover', models.CharField(default='#FFDFAF', max_length=7, validators=[django.core.validators.RegexValidator(message='Usa un color hexadecimal, ej. #0D9488', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='acento secundario — hover')),
                ('color_on_accent_secondary', models.CharField(default='#241505', max_length=7, validators=[django.core.validators.RegexValidator(message='Usa un color hexadecimal, ej. #0D9488', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='texto sobre el acento secundario')),
                ('color_danger', models.CharField(default='#EF4444', max_length=7, validators=[django.core.validators.RegexValidator(message='Usa un color hexadecimal, ej. #0D9488', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='color de error/baneo')),
                ('color_success', models.CharField(default='#22C55E', max_length=7, validators=[django.core.validators.RegexValidator(message='Usa un color hexadecimal, ej. #0D9488', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='color de éxito')),
                ('font_heading', models.CharField(default="'Playfair Display', Georgia, serif", max_length=200, verbose_name='fuente de titulares')),
                ('font_body', models.CharField(default="'Inter', system-ui, -apple-system, sans-serif", max_length=200, verbose_name='fuente de texto')),
                ('space_unit', models.CharField(default='0.25rem', max_length=20, verbose_name='unidad de espaciado base')),
                ('radius_base', models.CharField(default='0.6rem', max_length=20, verbose_name='radio de esquinas')),
                ('max_content_width', models.CharField(default='1200px', max_length=20, verbose_name='ancho máximo de contenido')),
                ('is_dark', models.BooleanField(default=True, help_text='Afecta al renderizado nativo de formularios/scrollbars del navegador.', verbose_name='esquema oscuro')),
            ],
            options={
                'verbose_name': 'tema visual',
                'verbose_name_plural': 'temas visuales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(default='Cine, debate y recomendaciones con acento propio.', max_length=200, verbose_name='eslogan')),
                ('require_email_verification', models.BooleanField(default=False, help_text='Si está activado, los usuarios nuevos deben confirmar su email antes de iniciar sesión.', verbose_name='exigir verificación de email al registrarse')),
                ('contact_email', models.EmailField(blank=True, help_text='Dirección a la que llegan los mensajes del formulario de contacto.', max_length=254, verbose_name='email de contacto')),
                ('active_theme', models.ForeignKey(blank=True, help_text='Tema que se aplica a toda la web salvo que un usuario elija otro en su perfil.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.theme', verbose_name='tema activo')),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
                'verbose_name_plural': 'Configuración del sitio',
            },
        ),
    ]
