# Generated by Django 6.0.7 on 2026-07-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_themes'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='bizum_number',
            field=models.CharField(blank=True, default='684 127 181', help_text='Se muestra en el cartel de donaciones. Formato libre (espacios incluidos).', max_length=20, verbose_name='número de Bizum'),
        ),
    ]
