# Generated by Django 6.0.7 on 2026-07-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_siteconfig_bizum_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='show_intro_animation',
            field=models.BooleanField(default=True, help_text='Se muestra una vez por sesión de navegador. Desactívala para quitarla de toda la web.', verbose_name='mostrar animación de proyector al entrar'),
        ),
    ]
