# Generated by Django 6.0.7 on 2026-07-28 13:55

from django.db import migrations, models

OLD_DEFAULT = "Cine, debate y recomendaciones con acento propio."
NEW_DEFAULT = "Cine, pelis, series y debates. Todo en una misma sala."


def update_existing_default_tagline(apps, schema_editor):
    # Solo se actualiza si el eslogan sigue siendo el valor de fábrica: si ya
    # se personalizó desde el admin, se respeta tal cual.
    SiteConfig = apps.get_model("core", "SiteConfig")
    SiteConfig.objects.filter(tagline=OLD_DEFAULT).update(tagline=NEW_DEFAULT)


def revert_default_tagline(apps, schema_editor):
    SiteConfig = apps.get_model("core", "SiteConfig")
    SiteConfig.objects.filter(tagline=NEW_DEFAULT).update(tagline=OLD_DEFAULT)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_siteconfig_show_intro_animation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='tagline',
            field=models.CharField(default=NEW_DEFAULT, max_length=200, verbose_name='eslogan'),
        ),
        migrations.RunPython(update_existing_default_tagline, revert_default_tagline),
    ]
