# Generated by Django 6.0.7 on 2026-07-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_update_default_tagline'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('twitter', 'Twitter/X'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('telegram', 'Telegram'), ('discord', 'Discord'), ('email', 'Email'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='plataforma')),
                ('label', models.CharField(help_text='Lo que se ve en el botón, ej: @lasaladebygui', max_length=100, verbose_name='usuario o nombre a mostrar')),
                ('url', models.URLField(help_text='A dónde lleva al pulsarlo: perfil, https://wa.me/34..., mailto:..., etc.', verbose_name='enlace')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'enlace de contacto',
                'verbose_name_plural': 'Sitio: enlaces de contacto',
                'ordering': ['order', 'id'],
            },
        ),
    ]
