# Generated by Django 6.0.7 on 2026-07-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contactlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactlink',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('twitter', 'Twitter/X'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('telegram', 'Telegram'), ('discord', 'Discord'), ('spotify', 'Spotify'), ('email', 'Email'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='plataforma'),
        ),
    ]
