# Generated by Django 6.0.7 on 2026-08-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_contactlink_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Si lo desmarcas, desaparece del selector de temas del sitio (pero sigue funcionando para quien ya lo tuviera puesto, y se puede seguir usando como tema activo del sitio desde Configuración del sitio).', verbose_name='publicado'),
        ),
    ]
