# Generated by Django 6.0.7 on 2026-08-08 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_seed_blanco_y_negro_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='color_intro_light',
            field=models.CharField(default='#FFDFAF', max_length=7, validators=[django.core.validators.RegexValidator(message='Usa un color hexadecimal, ej. #0D9488', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='luz del proyector en la animación de inicio'),
        ),
    ]
