# Generated by Django 6.0.7 on 2026-08-08 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_theme_color_intro_light'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='color_intro_chair',
            field=models.CharField(default='#8D7FCB', max_length=7, validators=[django.core.validators.RegexValidator(message='Usa un color hexadecimal, ej. #0D9488', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='sillón en la animación de inicio'),
        ),
        migrations.AddField(
            model_name='theme',
            name='color_intro_lamp',
            field=models.CharField(default='#B4A9E8', max_length=7, validators=[django.core.validators.RegexValidator(message='Usa un color hexadecimal, ej. #0D9488', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='lámpara en la animación de inicio'),
        ),
    ]
