# Generated by Django 6.0.7 on 2026-08-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_theme_color_intro_chair_theme_color_intro_lamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['order', 'name'], 'verbose_name': 'tema visual', 'verbose_name_plural': 'temas visuales'},
        ),
        migrations.AddField(
            model_name='theme',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Orden en el que aparece en el selector de temas — menor va primero.', verbose_name='orden'),
        ),
    ]
