# Generated by Django 6.0.7 on 2026-08-10 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_theme_options_theme_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='título')),
                ('body', models.TextField(blank=True, verbose_name='mensaje')),
                ('url', models.CharField(blank=True, help_text='Opcional — a dónde lleva al pulsarlo. Puede ser una ruta interna (/articulos/) o una URL completa.', max_length=300, verbose_name='enlace')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='publicado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='publicado por')),
                ('read_by', models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='leído por')),
            ],
            options={
                'verbose_name': 'aviso',
                'verbose_name_plural': 'Sitio: avisos',
                'ordering': ['-created_at'],
            },
        ),
    ]
