# Generated by Django 6.0.7 on 2026-08-11 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='require_email_verification',
        ),
    ]
