# Generated by Django 6.0.7 on 2026-08-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_siteconfig_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='intro_sound',
            field=models.FileField(blank=True, help_text='Opcional — un mp3/ogg/wav corto. Si lo subes, sustituye al sonido de carrete generado por defecto. Déjalo vacío para volver al de siempre.', upload_to='intro_sound/', verbose_name='sonido de la intro'),
        ),
    ]
