# Generated by Django 6.0.7 on 2026-08-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_siteconfig_intro_sound'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='notifications_bell_enabled',
            field=models.BooleanField(default=True, help_text='Desactívala para quitar la campanita de avisos de toda la web (mensajes, amistad, artículos, tienda...).', verbose_name='activar campanita de avisos'),
        ),
    ]
