# Generated by Django 6.0.7 on 2026-08-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_siteconfig_notifications_bell_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='recent_activity_enabled',
            field=models.BooleanField(default=True, help_text='Últimos comentarios de Artículos y del Foro, mezclados por fecha, en la sala principal.', verbose_name='mostrar actividad reciente en la portada'),
        ),
    ]
