# Generated by Django 6.0.8 on 2026-08-12 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_siteconfig_recent_activity_enabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at'], 'verbose_name': 'aviso', 'verbose_name_plural': 'avisos'},
        ),
        migrations.AlterModelOptions(
            name='contactlink',
            options={'ordering': ['order', 'id'], 'verbose_name': 'enlace de contacto', 'verbose_name_plural': 'enlaces de contacto'},
        ),
    ]
