# Generated by Django 6.0.8 on 2026-08-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_announcement_options_alter_contactlink_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='frase')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='película o serie')),
                ('notes', models.TextField(blank=True, help_text='Contexto, por qué te gustó, quién la dice...', verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
            ],
            options={
                'verbose_name': 'frase favorita',
                'verbose_name_plural': 'frases favoritas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='título')),
                ('body', models.TextField(blank=True, verbose_name='apunte')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última edición')),
            ],
            options={
                'verbose_name': 'apunte personal',
                'verbose_name_plural': 'apuntes personales',
                'ordering': ['-updated_at'],
            },
        ),
    ]
