# Generated by Django 6.0.8 on 2026-08-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_favoritequote_personalnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMenuOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.JSONField(blank=True, default=list, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'orden del menú del admin',
                'verbose_name_plural': 'orden del menú del admin',
            },
        ),
    ]
