# Generated by Django 6.0.8 on 2026-08-14 08:01, edited by hand to preserve
# any "order" data already saved from the antiguo mecanismo (lista plana)
# convirtiéndola a la nueva estructura de secciones antes de borrar el
# campo viejo.

from django.db import migrations, models


def convert_order_to_sections(apps, schema_editor):
    AdminMenuOrder = apps.get_model("core", "AdminMenuOrder")
    obj = AdminMenuOrder.objects.filter(pk=1).first()
    if not obj or not obj.order:
        return

    sections = []
    current = None
    for token in obj.order:
        if "." not in token:
            current = {"name": token, "items": []}
            sections.append(current)
        elif current is not None:
            current["items"].append(token)
    obj.sections = sections
    obj.save(update_fields=["sections"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_seed_more_themes'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmenuorder',
            name='sections',
            field=models.JSONField(blank=True, default=list, verbose_name='secciones'),
        ),
        migrations.RunPython(convert_order_to_sections, noop),
        migrations.RemoveField(
            model_name='adminmenuorder',
            name='order',
        ),
    ]
