# Generated by Django 6.0.7 on 2026-07-26 09:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.PositiveIntegerField(unique=True, verbose_name='id de TMDb')),
                ('imdb_id', models.CharField(blank=True, max_length=20, verbose_name='id de IMDb')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('year', models.CharField(blank=True, max_length=4, verbose_name='año')),
                ('poster_path', models.CharField(blank=True, max_length=300, verbose_name='ruta de portada (TMDb)')),
                ('overview', models.TextField(blank=True, verbose_name='sinopsis')),
                ('imdb_rating', models.DecimalField(blank=True, decimal_places=1, help_text='Obtenida de OMDb (omdbapi.com). Vacía si OMDb no tiene nota para este título.', max_digits=3, null=True, verbose_name='nota IMDb')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='añadida')),
            ],
            options={
                'verbose_name': 'película',
                'verbose_name_plural': 'películas',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='RouletteCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seen', models.BooleanField(default=False, verbose_name='ya salió en la ruleta')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roulette_candidates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'candidata de ruleta (lista personal)',
                'verbose_name_plural': 'candidatas de ruleta (lista personal)',
                'ordering': ['-added_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'movie'), name='una_candidata_por_usuario')],
            },
        ),
        migrations.CreateModel(
            name='RouletteRatingSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'película vista en ruleta (modo nota)',
                'verbose_name_plural': 'películas vistas en ruleta (modo nota)',
                'constraints': [models.UniqueConstraint(fields=('user', 'movie'), name='una_vista_por_usuario_modo_nota')],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'voto',
                'verbose_name_plural': 'votos',
                'constraints': [models.UniqueConstraint(fields=('movie', 'user'), name='un_voto_por_usuario_y_pelicula')],
            },
        ),
    ]
