# Generated by Django 6.0.7 on 2026-07-27 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_savedmovie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RouletteSavedSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'película vista en ruleta (modo lista)',
                'verbose_name_plural': 'películas vistas en ruleta (modo lista)',
            },
        ),
        migrations.RemoveConstraint(
            model_name='roulettecandidate',
            name='una_candidata_por_usuario',
        ),
        migrations.AddField(
            model_name='roulettesavedseen',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='roulettesavedseen',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='roulettecandidate',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='roulettecandidate',
            name='user',
        ),
        migrations.AddConstraint(
            model_name='roulettesavedseen',
            constraint=models.UniqueConstraint(fields=('user', 'movie'), name='una_vista_por_usuario_modo_lista'),
        ),
        migrations.DeleteModel(
            name='RouletteCandidate',
        ),
    ]
