# Generated by Django 6.0.7 on 2026-08-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_roulettesavedseen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='media_type',
            field=models.CharField(choices=[('movie', 'Película'), ('tv', 'Serie')], default='movie', max_length=5, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdb_id',
            field=models.PositiveIntegerField(verbose_name='id de TMDb'),
        ),
        migrations.AddConstraint(
            model_name='movie',
            constraint=models.UniqueConstraint(fields=('tmdb_id', 'media_type'), name='unico_tmdb_id_por_tipo'),
        ),
    ]
