# Generated by Django 6.0.7 on 2026-08-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_media_type_alter_movie_tmdb_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedmovie',
            options={'ordering': ['order', '-saved_at'], 'verbose_name': 'película guardada', 'verbose_name_plural': 'películas guardadas'},
        ),
        migrations.AddField(
            model_name='savedmovie',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='orden de importancia'),
        ),
    ]
