# Generated by Django 6.0.7 on 2026-08-01 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_savedmovie_options_savedmovie_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='fecha')),
                ('note', models.CharField(blank=True, help_text="Ej: 'Estreno', 'Temporada 2', 'Capítulo final'...", max_length=200, verbose_name='nota')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_events', to='movies.movie', verbose_name='película/serie')),
            ],
            options={
                'verbose_name': 'estreno en el calendario',
                'verbose_name_plural': 'calendario: estrenos',
                'ordering': ['date'],
            },
        ),
    ]
