# Generated by Django 6.0.7 on 2026-08-02 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_releaseevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseEventGoogleLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_event_id', models.CharField(max_length=255, verbose_name='id del evento en Google')),
                ('release_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_links', to='movies.releaseevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'estreno enlazado a Google Calendar',
                'verbose_name_plural': 'calendario: enlaces a Google Calendar',
                'constraints': [models.UniqueConstraint(fields=('release_event', 'user'), name='un_evento_de_google_por_usuario')],
            },
        ),
    ]
