# Generated by Django 6.0.7 on 2026-08-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_releaseeventgooglelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarDayNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='fecha')),
                ('note', models.CharField(max_length=280, verbose_name='comentario')),
            ],
            options={
                'verbose_name': 'comentario del calendario',
                'verbose_name_plural': 'calendario: comentarios de días',
                'ordering': ['date'],
            },
        ),
    ]
