# Generated by Django 6.0.7 on 2026-08-03 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_calendardaynote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedMovieList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='nombre')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_movie_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sublista de guardadas',
                'verbose_name_plural': 'sublistas de guardadas',
                'ordering': ['user_id', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='savedmovie',
            name='sublist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_movies', to='movies.savedmovielist', verbose_name='sublista'),
        ),
        migrations.AddConstraint(
            model_name='savedmovielist',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='una_sublista_por_nombre_y_usuario'),
        ),
    ]
