# Generated by Django 6.0.7 on 2026-08-03 17:31

from django.db import migrations, models


def copiar_sublista_a_sublistas(apps, schema_editor):
    """Antes cada guardada solo podía estar en una sublista (FK); ahora
    puede estar en varias a la vez (ManyToMany). Se traslada la asignación
    que ya hubiera antes de borrar el campo viejo, para no perderla."""
    SavedMovie = apps.get_model("movies", "SavedMovie")
    for saved in SavedMovie.objects.exclude(sublist__isnull=True):
        saved.sublists.add(saved.sublist_id)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_calendario_personal_esquema'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedmovie',
            name='sublists',
            field=models.ManyToManyField(blank=True, related_name='saved_movies', to='movies.savedmovielist', verbose_name='sublistas'),
        ),
        migrations.RunPython(copiar_sublista_a_sublistas, noop),
        migrations.RemoveField(
            model_name='savedmovie',
            name='sublist',
        ),
    ]
