# Generated by Django 6.0.7 on 2026-08-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_remove_savedmovie_sublist_savedmovie_sublists'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedmovielist',
            options={'ordering': ['user_id', 'order', 'name'], 'verbose_name': 'lista de guardadas', 'verbose_name_plural': 'listas de guardadas'},
        ),
        migrations.AlterField(
            model_name='savedmovie',
            name='sublists',
            field=models.ManyToManyField(blank=True, related_name='saved_movies', to='movies.savedmovielist', verbose_name='listas'),
        ),
    ]
