# Generated by Django 6.0.7 on 2026-08-04 17:37, hand-edited: el calendario
# (ReleaseEvent/CalendarDayNote) se muda de app (movies -> secret) porque es
# una sección de Top Secret, no de Películas — pero las tablas físicas
# siguen siendo las mismas (movies_releaseevent/movies_calendardaynote, ver
# el Meta.db_table en apps.secret.models), así que aquí solo cambia el
# estado de Django, nunca la base de datos real.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_alter_savedmovielist_options_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='calendardaynote',
                    name='un_comentario_por_usuario_y_fecha',
                ),
                migrations.RemoveField(
                    model_name='calendardaynote',
                    name='user',
                ),
                migrations.DeleteModel(
                    name='ReleaseEvent',
                ),
                migrations.DeleteModel(
                    name='CalendarDayNote',
                ),
            ],
            database_operations=[],
        ),
    ]
