# Generated by Django 6.0.7 on 2026-08-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_remove_calendardaynote_un_comentario_por_usuario_y_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='revenue',
            field=models.BigIntegerField(blank=True, help_text='Obtenida de TMDb. Solo para películas — TMDb no tiene este dato para series.', null=True, verbose_name='recaudación (USD)'),
        ),
    ]
