# Generated by Django 6.0.7 on 2026-08-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articleview'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Solo lo ven Gestores y Admin — el resto ni siquiera sabe que existe.', verbose_name='privado'),
        ),
    ]
