# Generated by Django 6.0.7 on 2026-08-10 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_is_private'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='idea')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('is_done', models.BooleanField(default=False, verbose_name='ya escrito')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='apuntada')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='apuntada por')),
            ],
            options={
                'verbose_name': 'idea de artículo',
                'verbose_name_plural': 'Artículos: ideas',
                'ordering': ['is_done', '-created_at'],
            },
        ),
    ]
