# Generated by Django 6.0.8 on 2026-08-12 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_articleidea'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleidea',
            options={'ordering': ['is_done', '-created_at'], 'verbose_name': 'idea de artículo', 'verbose_name_plural': 'ideas de artículo'},
        ),
    ]
