# Generated by Django 6.0.8 on 2026-08-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_articleidea_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Aparece en el carrusel de la portada. Si no marcas ninguno, se usan los más recientes.', verbose_name='destacado'),
        ),
    ]
