# Generated by Django 6.0.8 on 2026-08-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_is_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['order', 'name'], 'verbose_name': 'lista', 'verbose_name_plural': 'listas'},
        ),
        migrations.AddField(
            model_name='tag',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='orden'),
        ),
    ]
