# Generated by Django 6.0.7 on 2026-07-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop/products/', verbose_name='imagen')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='precio orientativo')),
                ('url', models.URLField(blank=True, verbose_name='enlace externo (opcional)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'artículo',
                'verbose_name_plural': 'Tienda: artículos',
                'ordering': ['order', 'name'],
            },
        ),
    ]
