# Generated by Django 6.0.8 on 2026-08-12 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order', 'name'], 'verbose_name': 'artículo', 'verbose_name_plural': 'artículos'},
        ),
    ]
