# Generated by Django 6.0.8 on 2026-09-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productview'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Los artículos ocultos no aparecen en el escaparate público, pero se conservan aquí.', verbose_name='visible en la tienda'),
        ),
    ]
