# Generated by Django 6.0.7 on 2026-07-26 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('body', models.TextField(verbose_name='mensaje')),
                ('is_locked', models.BooleanField(default=False, help_text='Si está cerrado, ya no se pueden añadir comentarios (moderación).', verbose_name='cerrado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
            ],
            options={
                'verbose_name': 'hilo',
                'verbose_name_plural': 'hilos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreadComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='comentario')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='eliminado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forum.threadcomment')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forum.thread')),
            ],
            options={
                'verbose_name': 'comentario de foro',
                'verbose_name_plural': 'comentarios de foro',
                'ordering': ['created_at'],
            },
        ),
    ]
