# Generated by Django 6.0.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_contact',
            field=models.BooleanField(default=False, help_text='Llegó desde el formulario de contacto, no escrito a mano en un chat.', verbose_name='mensaje de «Escríbenos»'),
        ),
    ]
