# Generated by Django 6.0.8

from django.db import migrations
from django.db.models import F


def fix_self_sent_contact_messages(apps, schema_editor):
    """Antes de esta versión, "Escríbenos" autoenviaba el mensaje al propio
    admin (sender == recipient): abrir esa conversación siempre daba 404
    (`apps.social.views.conversation` exige amistad, y nadie es amigo de sí
    mismo) y el mensaje nunca llegaba a marcarse como leído, así que se
    quedaba para siempre en la campanita de avisos. Aquí se reasignan esos
    mensajes sueltos al Buzón de contacto para que queden como una
    conversación normal, abrible y marcable como leída."""
    from apps.social.models import Message, ensure_friends, get_contact_bot_user

    stuck = list(Message.objects.filter(sender_id=F("recipient_id")))
    if not stuck:
        return

    bot = get_contact_bot_user()
    for message in stuck:
        ensure_friends(bot, message.recipient)
        message.sender = bot
        message.is_contact = True
        message.save(update_fields=["sender", "is_contact"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_message_is_contact'),
    ]

    operations = [
        migrations.RunPython(fix_self_sent_contact_messages, noop_reverse),
    ]
