# Generated by Django 6.0.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_fix_contact_self_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='contact_name',
            field=models.CharField(blank=True, help_text='Solo en mensajes de «Escríbenos»: cómo se identificó quien escribió, para poder distinguir remitentes cuando todos comparten el Buzón de contacto.', max_length=120, verbose_name='nombre de quien escribió'),
        ),
        migrations.AddField(
            model_name='message',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email de quien escribió'),
        ),
    ]
