# Generated by Django 6.0.8

import re

from django.db import migrations

_CONTACT_PREFIX_RE = re.compile(r"^Mensaje de «Escríbenos» de (?P<name>.+?) <(?P<email>[^<>]+?)>:\n\n(?P<rest>.*)", re.DOTALL)


def backfill_contact_name(apps, schema_editor):
    """Los mensajes de "Escríbenos" de antes de que existieran
    `contact_name`/`contact_email` llevaban esa info metida a mano en el
    propio texto ("Mensaje de «Escríbenos» de X <Y>:\n\n..."). Aquí se
    extrae a los campos nuevos y se limpia el texto para que quede solo el
    mensaje de verdad, igual que los que se creen a partir de ahora."""
    Message = apps.get_model("social", "Message")

    for message in Message.objects.filter(is_contact=True, contact_name=""):
        match = _CONTACT_PREFIX_RE.match(message.body)
        if not match:
            continue
        message.contact_name = match.group("name").strip()[:120]
        message.contact_email = match.group("email").strip()[:254]
        message.body = match.group("rest")
        message.save(update_fields=["contact_name", "contact_email", "body"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_message_contact_name_message_contact_email'),
    ]

    operations = [
        migrations.RunPython(backfill_contact_name, noop_reverse),
    ]
